# -*- coding: utf-8 -*-
"""fine_tuning_GoT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJd97pa2mh-H8eVNLVH8r1wv8wtME5tT
"""

!pip install -q openai

from google.colab import drive
drive.mount('/content/drive')

import os
import openai
from pathlib import Path
from openai import OpenAI

client = OpenAI(api_key = "xx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

import os
import openai
from pathlib import Path
from openai import OpenAI

client = OpenAI(api_key = "xx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

client.files.create(
    file=Path("/content/drive/MyDrive/dataset_.jsonl"),
    purpose="fine-tune",
)

client.fine_tuning.jobs.create(training_file="file-e1FLzWvFrr58GREoMaK7Z2ry", model="davinci-002")

client.fine_tuning.jobs.retrieve("ftjob-Bwx7kiDwHe0BjvmquL9kXVz1")



response = client.chat.completions.create(
  model="gpt-4",
  messages=[
      {"role": "system", "content": "You are an IoT security Guardian."},
    {"role": "user", "content": "How to detect a DDOS attack on a Rapberry pi server"},
    {"role": "assistant", "content": "using hping3 and checkstatusestimate the impact of a DDOS attack on a Raspberry pi server using hping3 and checkstatus in Kali Linux. Implement defense mechanisms to mitigate such threats. Read MoreUsePrometheusandGrafanafor server and application monitoringCollect and visualize server and application metrics using Prometheus and Grafana. Identify performance bottlenecks and troubleshoot issues proactively. Read Morein Kali Linux. Implement defense mechanisms to mitigate such threats. Read MoreResearchand"},
    {"role": "user", "content":"Write a clean python script for How to detect a DDOS attack on a Rapberry pi server using these steps: using hping3 and checkstatusestimate the impact of a DDOS attack on a Raspberry pi server using hping3 and checkstatus in Kali Linux. Implement defense mechanisms to mitigate such threats. Read MoreUsePrometheusandGrafanafor server and application monitoringCollect and visualize server and application metrics using Prometheus and Grafana. Identify performance bottlenecks and troubleshoot issues proactively. Read Morein Kali Linux. Implement defense mechanisms to mitigate such threats. Read MoreResearchand"}
  ]
)
print(response.choices[0].message.content)

response = client.completions.create(
  model="gpt-3.5-turbo-instruct",
  prompt="Write a clean python script for deauthentication attack on an Amazon Alexa using these steps :tep 1: Jailbreak your Amazon Echo device using Venom Monkey. … Step 2: Run the airdrop-ng attack module using Kali Linux. … Step 3: Monitor the network for the deauthentication packets. … Step 4: Check if the deauthentication attack was successful ",
  max_tokens = 250
)

print(response.choices[0].text)

completion = client.completions.create(
    model='ft:davinci-002:personal::8PYXvH5y',
    prompt="How to do a deauthentication attack on an Amazon Alexa",
    max_tokens = 100
)

print(completion.choices[0].text)

response = client.completions.create(
  model="gpt-3.5-turbo-instruct",
  prompt="Write a clean python script for deauthentication attack on an Amazon Alexa using these steps :tep 1: Jailbreak your Amazon Echo device using Venom Monkey. … Step 2: Run the airdrop-ng attack module using Kali Linux. … Step 3: Monitor the network for the deauthentication packets. … Step 4: Check if the deauthentication attack was successful ",
  max_tokens = 250
)

print(response.choices[0].text)

completion = client.completions.create(
    model='ft:davinci-002:personal::8PYXvH5y',
    prompt="How to do a crack TP-link wifi password",
    max_tokens = 100
)

print(completion.choices[0].text)

response = client.completions.create(
  model="gpt-3.5-turbo-instruct",
  prompt="Write a clean python script for crack TP-link wifi password using these steps crack TP-link wifi password",
  max_tokens = 250
)

print(response.choices[0].text)

completion = client.completions.create(
    model='ft:davinci-002:personal::8PYXvH5y',
    prompt="How to detect a DDOS attack on a Rapberry pi server",
    max_tokens = 100
)

print(completion.choices[0].text)

response = client.completions.create(
  model="gpt-3.5-turbo-instruct",
  prompt="Write a clean python script for detecting a DDOS attack on a Rapberry pi server using these steps :  using hping3 and checkstatusestimate the impact of a DDOS attack on a Raspberry pi server using hping3 and checkstatus in Kali Linux. Implement defense mechanisms to mitigate such threats. Read MoreUsePrometheusandGrafanafor server and application monitoringCollect and visualize server and application metrics using Prometheus and Grafana. Identify performance bottlenecks and troubleshoot issues proactively. Read Morein Kali Linux. Implement defense mechanisms to mitigate such threats.",
  max_tokens = 250
)

print(response.choices[0].text)

response = client.completions.create(
  model="gpt-3.5-turbo-instruct",
  prompt="Write a clean python script for detecting a DDOS attack on a Rapberry pi server using these steps :  using hping3 and checkstatusestimate the impact of a DDOS attack on a Raspberry pi server using hping3 and checkstatus in Kali Linux. Implement defense mechanisms to mitigate such threats. Read MoreUsePrometheusandGrafanafor server and application monitoringCollect and visualize server and application metrics using Prometheus and Grafana. Identify performance bottlenecks and troubleshoot issues proactively. Read Morein Kali Linux. Implement defense mechanisms to mitigate such threats.",
  max_tokens = 400
)

print(response.choices[0].text)

message = "How to prevent deauthentication attack on an IoT device"
completion = client.completions.create(
    model='ft:davinci-002:personal::8PYXvH5y',
    prompt=message,
    max_tokens = 200
)


print(completion.choices[0].text)

response = client.completions.create(
  model="gpt-3.5-turbo-instruct",
  prompt="Write a clean python script for defending raspberry pi from IoT attacks using these steps:use Kali Linux tools like zmap and Hive in Docker containers. Configure port security, update vulnerable software, and apply IoT security best practices for a more secure environment. Use tools like Burp Suite and OWASP ZAP in Kali Linux for web application security testing. Protect applications from vulnerabilities by conducting security audits and implementing secure coding practices. Test applications for SQL injection vulnerabilities using tools like sqlmap and Havij in Kali Linux's Metasploit framework. Follow secure coding practices and prevent SQL injections for secure web applications.",
  max_tokens = 1000
)

print(response.choices[0].text)

message = input("Enter issue : ")
instructions = ". Give output in proper steps."
completion = client.completions.create(
    model='ft:davinci-002:personal::8PYXvH5y',
    prompt=message,
    max_tokens = 1000
)


print(completion.choices[0].text)